name: Deployment
on:
  push:
    branches:
      - main
      - dev
jobs:
  build-and-deploy:
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DODOCO_BOT_PAT }}
        repository: trifoliumproj/deployment
        event-type: kustomization
        client-payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
